# Generated by Django 5.2.9 on 2025-12-08 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('min_percent', models.IntegerField()),
                ('max_percent', models.IntegerField()),
            ],
            options={
                'ordering': ['-min_percent'],
            },
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='iPhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PriceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(choices=[('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB')], max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('has_box', models.BooleanField(default=True, verbose_name='Quti bor')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="OXIRGI NARX (so'mda)")),
                ('note', models.TextField(blank=True, verbose_name='Qo‘shimcha izoh (ixtiyoriy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botapp.batteryrange')),
                ('damages', models.ManyToManyField(blank=True, to='botapp.damagetype', verbose_name='Shikastlangan qismlar')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='botapp.iphonemodel')),
            ],
            options={
                'verbose_name': 'Telefon narxi (to‘liq holat)',
                'verbose_name_plural': 'Telefon narxlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
