# Generated by Django 5.2.9 on 2025-12-08 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batteryrange',
            options={'ordering': ['-min_percent'], 'verbose_name': 'Batareya oraliq', 'verbose_name_plural': 'Batareya oraliqlar'},
        ),
        migrations.AlterModelOptions(
            name='damagetype',
            options={'ordering': ['name'], 'verbose_name': 'Shikast turi', 'verbose_name_plural': 'Shikast turlari'},
        ),
        migrations.AlterModelOptions(
            name='iphonemodel',
            options={'ordering': ['order'], 'verbose_name': 'iPhone Modeli', 'verbose_name_plural': 'iPhone Modellari'},
        ),
        migrations.AlterModelOptions(
            name='priceentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telefon narxi', 'verbose_name_plural': 'Telefon narxlari'},
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='label',
            field=models.CharField(max_length=20, unique=True, verbose_name='Oraliq nomi'),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='max_percent',
            field=models.IntegerField(verbose_name='Maksimal foiz'),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='min_percent',
            field=models.IntegerField(verbose_name='Minimal foiz'),
        ),
        migrations.AlterField(
            model_name='damagetype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Shikast turi'),
        ),
        migrations.AlterField(
            model_name='iphonemodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='iphonemodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Model nomi'),
        ),
        migrations.AlterField(
            model_name='iphonemodel',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='battery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botapp.batteryrange', verbose_name='Batareya holati'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Rang'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name="OXIRGI NARX (so'm)"),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='botapp.iphonemodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='note',
            field=models.TextField(blank=True, help_text='Masalan: 99% holat, full original', verbose_name='Qo‘shimcha izoh'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='storage',
            field=models.CharField(choices=[('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB')], max_length=20, verbose_name='Xotira hajmi'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
    ]
