# Generated by Django 5.2.9 on 2025-12-08 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_alter_batteryrange_options_alter_damagetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryrange',
            name='label',
            field=models.CharField(max_length=30, unique=True, verbose_name='Oraliq nomi'),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='max_percent',
            field=models.PositiveIntegerField(verbose_name='Maksimal foiz'),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='min_percent',
            field=models.PositiveIntegerField(verbose_name='Minimal foiz'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='final_price',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name="OXIRGI NARX (so'm)"),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='note',
            field=models.TextField(blank=True, help_text='Masalan: 99% holat, full original, vin toza', verbose_name='Qo‘shimcha izoh'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Rang nomi')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_colors', to='botapp.iphonemodel', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Ranglar',
                'ordering': ['model__name', 'name'],
                'unique_together': {('model', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botapp.color', verbose_name='Rang'),
        ),
    ]
