# Generated by Django 5.2.9 on 2025-12-08 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_alter_batteryrange_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Rang', 'verbose_name_plural': 'Ranglar'},
        ),
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colors/', verbose_name='Rang rasmi'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Rang nomi'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='note',
            field=models.TextField(blank=True, verbose_name='Qo‘shimcha izoh'),
        ),
        migrations.CreateModel(
            name='StorageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, verbose_name='Xotira hajmi')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='botapp.iphonemodel', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Xotira hajmi',
                'verbose_name_plural': 'Xotira hajmlari',
                'ordering': ['model', 'size'],
                'unique_together': {('model', 'size')},
            },
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botapp.storageoption', verbose_name='Xotira hajmi'),
        ),
    ]
