# Generated by Django 5.2.9 on 2025-12-08 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0004_alter_color_options_color_image_alter_color_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceentry',
            name='damages',
        ),
        migrations.RemoveField(
            model_name='priceentry',
            name='final_price',
        ),
        migrations.AddField(
            model_name='iphonemodel',
            name='default_sim_type',
            field=models.CharField(choices=[('physical', 'SIM karta'), ('esim', 'eSIM')], default='physical', help_text='iPhone 11-13: SIM karta, iPhone 14+: eSIM', max_length=20, verbose_name='SIM turi'),
        ),
        migrations.AddField(
            model_name='priceentry',
            name='base_price',
            field=models.DecimalField(decimal_places=0, default=1, help_text='Shikastsiz telefon narxi', max_digits=15, verbose_name="Asosiy narx (so'm)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceentry',
            name='sim_type',
            field=models.CharField(choices=[('physical', 'SIM karta'), ('esim', 'eSIM')], default=1, help_text='Odatda modelning default qiymatidan olinadi', max_length=20, verbose_name='SIM turi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='note',
            field=models.TextField(blank=True, verbose_name="Qo'shimcha izoh"),
        ),
        migrations.CreateModel(
            name='DamageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Guruh nomi')),
                ('price_discount', models.DecimalField(decimal_places=0, help_text='Bu shikast uchun asosiy narxdan qancha chegirma', max_digits=15, verbose_name="Narx chegirmasi (so'm)")),
                ('damages', models.ManyToManyField(to='botapp.damagetype', verbose_name='Shikastlar')),
            ],
            options={
                'verbose_name': 'Shikast guruhi',
                'verbose_name_plural': 'Shikast guruhlari',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='priceentry',
            name='damage_group',
            field=models.ForeignKey(blank=True, help_text="Agar shikast bo'lsa, guruhni tanlang", null=True, on_delete=django.db.models.deletion.SET_NULL, to='botapp.damagegroup', verbose_name='Shikast guruhi'),
        ),
    ]
