# Generated by Django 5.2.9 on 2025-12-08 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_remove_priceentry_damages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagegroup',
            name='price_discount',
        ),
        migrations.AddField(
            model_name='damagegroup',
            name='model',
            field=models.ForeignKey(default=1, help_text='Bu guruh qaysi model uchun', on_delete=django.db.models.deletion.CASCADE, related_name='damage_groups', to='botapp.iphonemodel', verbose_name='Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceentry',
            name='damage_discount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Shikast tufayli qancha arzonlashtirilgan', max_digits=15, verbose_name="Shikast uchun chegirma (so'm)"),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='botapp.color', verbose_name='Rang'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='damage_group',
            field=models.ForeignKey(blank=True, help_text="Qaysi shikastlar borligini ko'rsatish uchun", null=True, on_delete=django.db.models.deletion.SET_NULL, to='botapp.damagegroup', verbose_name='Shikast guruhi'),
        ),
    ]
