# Generated by Django 5.2.9 on 2025-12-09 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0006_remove_damagegroup_price_discount_damagegroup_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damagegroup',
            options={'ordering': ['model', 'name'], 'verbose_name': 'Shikast guruhi', 'verbose_name_plural': 'Shikast guruhlari'},
        ),
        migrations.RemoveField(
            model_name='priceentry',
            name='base_price',
        ),
        migrations.AddField(
            model_name='batteryrange',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='100% batareya standart', verbose_name='Standart (100%)'),
        ),
        migrations.AddField(
            model_name='batteryrange',
            name='price_difference',
            field=models.DecimalField(decimal_places=0, default=0, help_text='100% ga nisbatan. 95-99%=-500000, 90-94%=-1000000', max_digits=15, verbose_name="Narx farqi (so'm)"),
        ),
        migrations.AddField(
            model_name='color',
            name='color_type',
            field=models.CharField(choices=[('standard', 'Standart'), ('premium', 'Premium')], default='standard', max_length=20, verbose_name='Rang turi'),
        ),
        migrations.AddField(
            model_name='color',
            name='price_difference',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Premium rang bo'lsa qo'shimcha. Masalan: +500000", max_digits=15, verbose_name="Narx farqi (so'm)"),
        ),
        migrations.AddField(
            model_name='iphonemodel',
            name='base_standard_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Standart konfiguratsiya uchun narx (avtomatik hisoblash bazasi)', max_digits=15, verbose_name="Standart narx (so'm)"),
        ),
        migrations.AddField(
            model_name='priceentry',
            name='manual_adjustment',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Maxsus hollarda qo'shimcha +/- ", max_digits=15, verbose_name="Qo'lda sozlash (so'm)"),
        ),
        migrations.AddField(
            model_name='storageoption',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='256GB odatda standart', verbose_name='Standart xotira'),
        ),
        migrations.AddField(
            model_name='storageoption',
            name='price_difference',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Standart xotiraga nisbatan (+/-). 128GB=-2000000, 512GB=+3000000', max_digits=15, verbose_name="Narx farqi (so'm)"),
        ),
        migrations.AlterField(
            model_name='damagegroup',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_groups', to='botapp.iphonemodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='damage_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name="Shikast chegirmasi (so'm)"),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='damage_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botapp.damagegroup', verbose_name='Shikast guruhi'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='note',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='sim_type',
            field=models.CharField(choices=[('physical', 'SIM karta'), ('esim', 'eSIM')], max_length=20, verbose_name='SIM turi'),
        ),
        migrations.AlterUniqueTogether(
            name='damagegroup',
            unique_together={('model', 'name')},
        ),
    ]
