# Generated by Django 5.2.9 on 2025-12-09 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0007_alter_damagegroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batteryrange',
            options={'ordering': ['model', '-min_percent'], 'verbose_name': 'Batareya oraliq', 'verbose_name_plural': 'Batareya oraliqlar'},
        ),
        migrations.AddField(
            model_name='batteryrange',
            name='model',
            field=models.ForeignKey(default=1, help_text='Bu batareya oraliq qaysi model uchun', on_delete=django.db.models.deletion.CASCADE, related_name='battery_ranges', to='botapp.iphonemodel', verbose_name='Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iphonemodel',
            name='alternative_sim_price_difference',
            field=models.DecimalField(decimal_places=0, default=-200000, help_text="Standart bo'lmagan SIM tanlanganda farq. Masalan: -200000", max_digits=15, verbose_name="Boshqa SIM turi farqi (so'm)"),
        ),
        migrations.AddField(
            model_name='iphonemodel',
            name='box_price_difference',
            field=models.DecimalField(decimal_places=0, default=-300000, help_text="Quti yo'q bo'lsa qancha arzonroq. Masalan: -300000", max_digits=15, verbose_name="Quti yo'q farqi (so'm)"),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='Bu standart batareya holati (100%)', verbose_name='Standart (100%)'),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='label',
            field=models.CharField(max_length=30, verbose_name='Oraliq nomi'),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='price_difference',
            field=models.DecimalField(decimal_places=0, default=0, help_text='100% ga nisbatan. Past batareya = minus, masalan: 70-74% = -300000', max_digits=15, verbose_name="Narx farqi (so'm)"),
        ),
        migrations.AlterField(
            model_name='color',
            name='price_difference',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Standart rangga nisbatan. Premium kam bo'lsa minus, masalan: -200000", max_digits=15, verbose_name="Narx farqi (so'm)"),
        ),
        migrations.AlterField(
            model_name='iphonemodel',
            name='base_standard_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Eng yaxshi holat narxi: Eng katta xotira, 100% batareya, Quti bor, Standart SIM', max_digits=15, verbose_name="Standart narx (so'm)"),
        ),
        migrations.AlterField(
            model_name='iphonemodel',
            name='default_sim_type',
            field=models.CharField(choices=[('physical', 'SIM karta'), ('esim', 'eSIM')], default='physical', help_text='iPhone 11-13: SIM karta, iPhone 14+: eSIM', max_length=20, verbose_name='Standart SIM turi'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='manual_adjustment',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Maxsus hollarda qo'shimcha +/-", max_digits=15, verbose_name="Qo'lda sozlash (so'm)"),
        ),
        migrations.AlterField(
            model_name='storageoption',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='Bu standart (eng katta) xotira', verbose_name='Standart xotira'),
        ),
        migrations.AlterField(
            model_name='storageoption',
            name='price_difference',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Standart xotiraga nisbatan. Kichik xotira = minus, Masalan: 64GB=-600000', max_digits=15, verbose_name="Narx farqi (so'm)"),
        ),
        migrations.AlterUniqueTogether(
            name='batteryrange',
            unique_together={('model', 'label')},
        ),
    ]
