# Generated by Django 5.2.9 on 2025-12-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0008_alter_batteryrange_options_batteryrange_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphonemodel',
            name='damage_0_15_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Yengil shikast (tirnalishlar). Masalan: -50.00', max_digits=15, verbose_name='0-15% shikast chegirmasi ($)'),
        ),
        migrations.AddField(
            model_name='iphonemodel',
            name='damage_15_30_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="O'rta shikast (batareya/qopqoq). Masalan: -100.00", max_digits=15, verbose_name='15-30% shikast chegirmasi ($)'),
        ),
        migrations.AddField(
            model_name='iphonemodel',
            name='damage_30_50_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Og'ir shikast (ekran/plata). Masalan: -150.00", max_digits=15, verbose_name='30-50% shikast chegirmasi ($)'),
        ),
        migrations.AddField(
            model_name='priceentry',
            name='damage_percentage',
            field=models.CharField(choices=[('none', "Shikast yo'q (0%)"), ('0-15', '0-15% (Yengil - tirnalishlar)'), ('15-30', "15-30% (O'rta - batareya/qopqoq)"), ('30-50', "30-50% (Og'ir - ekran/plata)")], default='none', help_text='Telefon shikastlanish darajasi', max_length=10, verbose_name='Shikast darajasi'),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='price_difference',
            field=models.DecimalField(decimal_places=2, default=0, help_text='100% ga nisbatan (dollar). Masalan: 70-74% = -300', max_digits=15, verbose_name='Narx farqi ($)'),
        ),
        migrations.AlterField(
            model_name='color',
            name='price_difference',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standart rangga nisbatan (dollar). Masalan: -20', max_digits=15, verbose_name='Narx farqi ($)'),
        ),
        migrations.AlterField(
            model_name='iphonemodel',
            name='alternative_sim_price_difference',
            field=models.DecimalField(decimal_places=2, default=-5, help_text="Standart bo'lmagan SIM (dollar). Masalan: -5.00", max_digits=15, verbose_name='Boshqa SIM turi farqi ($)'),
        ),
        migrations.AlterField(
            model_name='iphonemodel',
            name='base_standard_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Eng yaxshi holat narxi DOLLAR da. Masalan: 1000.00', max_digits=15, verbose_name='Standart narx ($)'),
        ),
        migrations.AlterField(
            model_name='iphonemodel',
            name='box_price_difference',
            field=models.DecimalField(decimal_places=2, default=-10, help_text="Quti yo'q bo'lsa qancha arzonroq (dollar). Masalan: -10.00", max_digits=15, verbose_name="Quti yo'q farqi ($)"),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='damage_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Qo'lda qo'shimcha chegirma (dollar)", max_digits=15, verbose_name="Qo'shimcha shikast ($)"),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='manual_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Maxsus hollarda qo'shimcha +/- (dollar)", max_digits=15, verbose_name="Qo'lda sozlash ($)"),
        ),
        migrations.AlterField(
            model_name='storageoption',
            name='price_difference',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standart xotiraga nisbatan (dollar). Masalan: 64GB=-600', max_digits=15, verbose_name='Narx farqi ($)'),
        ),
    ]
