# Generated by Django 5.2.9 on 2025-12-10 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0009_iphonemodel_damage_0_15_discount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='damagegroup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='damagegroup',
            name='damages',
        ),
        migrations.RemoveField(
            model_name='damagegroup',
            name='model',
        ),
        migrations.RemoveField(
            model_name='priceentry',
            name='damage_group',
        ),
        migrations.AlterModelOptions(
            name='batteryrange',
            options={'ordering': ['model', '-min_percent']},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={},
        ),
        migrations.AlterModelOptions(
            name='storageoption',
            options={'ordering': ['model', 'size']},
        ),
        migrations.RemoveField(
            model_name='iphonemodel',
            name='damage_0_15_discount',
        ),
        migrations.RemoveField(
            model_name='iphonemodel',
            name='damage_15_30_discount',
        ),
        migrations.RemoveField(
            model_name='iphonemodel',
            name='damage_30_50_discount',
        ),
        migrations.RemoveField(
            model_name='priceentry',
            name='damage_discount',
        ),
        migrations.RemoveField(
            model_name='priceentry',
            name='damage_percentage',
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='is_standard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='max_percent',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='min_percent',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_ranges', to='botapp.iphonemodel'),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='price_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_type',
            field=models.CharField(choices=[('standard', 'Standart'), ('premium', 'Premium')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colors/'),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_colors', to='botapp.iphonemodel'),
        ),
        migrations.AlterField(
            model_name='color',
            name='price_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='iphonemodel',
            name='alternative_sim_price_difference',
            field=models.DecimalField(decimal_places=2, default=-5, max_digits=15, verbose_name='Boshqa SIM turi farqi ($)'),
        ),
        migrations.AlterField(
            model_name='iphonemodel',
            name='base_standard_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Standart narx ($)'),
        ),
        migrations.AlterField(
            model_name='iphonemodel',
            name='box_price_difference',
            field=models.DecimalField(decimal_places=2, default=-10, max_digits=15, verbose_name="Quti yo'q farqi ($)"),
        ),
        migrations.AlterField(
            model_name='iphonemodel',
            name='default_sim_type',
            field=models.CharField(choices=[('physical', 'SIM karta'), ('esim', 'eSIM')], default='physical', max_length=20, verbose_name='Standart SIM turi'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='battery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botapp.batteryrange'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='botapp.color'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='has_box',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='manual_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Qo'lda sozlash ($)"),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='botapp.iphonemodel'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='sim_type',
            field=models.CharField(choices=[('physical', 'SIM karta'), ('esim', 'eSIM')], max_length=20),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botapp.storageoption'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storageoption',
            name='is_standard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storageoption',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='botapp.iphonemodel'),
        ),
        migrations.AlterField(
            model_name='storageoption',
            name='price_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='ReplacedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('battery', 'Batareyka'), ('back_cover', 'Krishka'), ('speaker', 'Kalonka'), ('glass', 'Oyna'), ('screen', 'Ekran'), ('camera', 'Kamera'), ('broken', 'Qirilgan'), ('body', 'Korpus')], max_length=20, verbose_name='Qism nomi')),
                ('reference_price', models.DecimalField(decimal_places=2, default=0, help_text="Faqat ma'lumot. Aslida guruhda o'zgaradi. Masalan: -50", max_digits=15, verbose_name="Ma'lumot narxi ($)")),
                ('description', models.TextField(blank=True, verbose_name="Ta'rif")),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced_parts', to='botapp.iphonemodel', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Almashgan qism',
                'verbose_name_plural': 'Almashgan qismlar',
                'ordering': ['model', 'order', 'part_type'],
                'unique_together': {('model', 'part_type')},
            },
        ),
        migrations.CreateModel(
            name='ReplacedPartCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_reduction', models.DecimalField(decimal_places=2, default=0, help_text='Bu kombinatsiya uchun ANIQ narx. Masalan: Ekran+Qirilgan = -$100', max_digits=15, verbose_name='Narxdan ayriladi ($)')),
                ('combination_name', models.CharField(help_text='Avtomatik: Ekran + Batareyka + Qirilgan', max_length=300, verbose_name='Kombinatsiya nomi')),
                ('part_count', models.IntegerField(default=0, help_text='2, 3, 4, ...', verbose_name='Qismlar soni')),
                ('note', models.TextField(blank=True, help_text="Masalan: Eng ko'p uchraydi, Maxsus chegirma", verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_combinations', to='botapp.iphonemodel', verbose_name='Model')),
                ('parts', models.ManyToManyField(help_text='Bu kombinatsiyadagi qismlar', to='botapp.replacedpart', verbose_name='Qismlar')),
            ],
            options={
                'verbose_name': 'Qismlar kombinatsiyasi',
                'verbose_name_plural': 'Qismlar kombinatsiyalari',
                'ordering': ['model', 'part_count', 'combination_name'],
                'unique_together': {('model', 'combination_name')},
            },
        ),
        migrations.AddField(
            model_name='priceentry',
            name='replaced_combination',
            field=models.ForeignKey(blank=True, help_text='Tayyor kombinatsiyadan tanlang', null=True, on_delete=django.db.models.deletion.SET_NULL, to='botapp.replacedpartcombination', verbose_name='Almashgan qismlar kombinatsiyasi'),
        ),
        migrations.DeleteModel(
            name='DamageType',
        ),
        migrations.DeleteModel(
            name='DamageGroup',
        ),
    ]
