# Generated by Django 5.2.9 on 2025-12-10 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0010_alter_damagegroup_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Shikast turi')),
            ],
            options={
                'verbose_name': 'Shikast turi',
                'verbose_name_plural': 'Shikast turlari',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='replacedpartcombination',
            name='parts',
        ),
        migrations.AlterUniqueTogether(
            name='replacedpartcombination',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='replacedpartcombination',
            name='model',
        ),
        migrations.RemoveField(
            model_name='priceentry',
            name='replaced_combination',
        ),
        migrations.AlterModelOptions(
            name='batteryrange',
            options={'ordering': ['model', '-min_percent'], 'verbose_name': 'Batareya oraliq', 'verbose_name_plural': 'Batareya oraliqlar'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Rang', 'verbose_name_plural': 'Ranglar'},
        ),
        migrations.AlterModelOptions(
            name='storageoption',
            options={'ordering': ['model', 'size'], 'verbose_name': 'Xotira hajmi', 'verbose_name_plural': 'Xotira hajmlari'},
        ),
        migrations.AddField(
            model_name='iphonemodel',
            name='damage_0_15_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Yengil shikast (tirnalishlar). Masalan: -50.00', max_digits=15, verbose_name='0-15% shikast chegirmasi ($)'),
        ),
        migrations.AddField(
            model_name='iphonemodel',
            name='damage_15_30_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="O'rta shikast (batareya/qopqoq). Masalan: -100.00", max_digits=15, verbose_name='15-30% shikast chegirmasi ($)'),
        ),
        migrations.AddField(
            model_name='iphonemodel',
            name='damage_30_50_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Og'ir shikast (ekran/plata). Masalan: -150.00", max_digits=15, verbose_name='30-50% shikast chegirmasi ($)'),
        ),
        migrations.AddField(
            model_name='priceentry',
            name='damage_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Qo'lda qo'shimcha chegirma (dollar)", max_digits=15, verbose_name="Qo'shimcha shikast ($)"),
        ),
        migrations.AddField(
            model_name='priceentry',
            name='damage_percentage',
            field=models.CharField(choices=[('none', "Shikast yo'q (0%)"), ('0-15', '0-15% (Yengil - tirnalishlar)'), ('15-30', "15-30% (O'rta - batareya/qopqoq)"), ('30-50', "30-50% (Og'ir - ekran/plata)")], default='none', help_text='Telefon shikastlanish darajasi', max_length=10, verbose_name='Shikast darajasi'),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='Bu standart batareya holati (100%)', verbose_name='Standart (100%)'),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='max_percent',
            field=models.PositiveIntegerField(verbose_name='Maksimal foiz'),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='min_percent',
            field=models.PositiveIntegerField(verbose_name='Minimal foiz'),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='model',
            field=models.ForeignKey(help_text='Bu batareya oraliq qaysi model uchun', on_delete=django.db.models.deletion.CASCADE, related_name='battery_ranges', to='botapp.iphonemodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='batteryrange',
            name='price_difference',
            field=models.DecimalField(decimal_places=2, default=0, help_text='100% ga nisbatan (dollar). Masalan: 70-74% = -300', max_digits=15, verbose_name='Narx farqi ($)'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_type',
            field=models.CharField(choices=[('standard', 'Standart'), ('premium', 'Premium')], default='standard', max_length=20, verbose_name='Rang turi'),
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colors/', verbose_name='Rang rasmi'),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_colors', to='botapp.iphonemodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='color',
            name='price_difference',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standart rangga nisbatan (dollar). Masalan: -20', max_digits=15, verbose_name='Narx farqi ($)'),
        ),
        migrations.AlterField(
            model_name='iphonemodel',
            name='alternative_sim_price_difference',
            field=models.DecimalField(decimal_places=2, default=-5, help_text="Standart bo'lmagan SIM (dollar). Masalan: -5.00", max_digits=15, verbose_name='Boshqa SIM turi farqi ($)'),
        ),
        migrations.AlterField(
            model_name='iphonemodel',
            name='base_standard_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Eng yaxshi holat narxi DOLLAR da. Masalan: 1000.00', max_digits=15, verbose_name='Standart narx ($)'),
        ),
        migrations.AlterField(
            model_name='iphonemodel',
            name='box_price_difference',
            field=models.DecimalField(decimal_places=2, default=-10, help_text="Quti yo'q bo'lsa qancha arzonroq (dollar). Masalan: -10.00", max_digits=15, verbose_name="Quti yo'q farqi ($)"),
        ),
        migrations.AlterField(
            model_name='iphonemodel',
            name='default_sim_type',
            field=models.CharField(choices=[('physical', 'SIM karta'), ('esim', 'eSIM')], default='physical', help_text='iPhone 11-13: SIM karta, iPhone 14+: eSIM', max_length=20, verbose_name='Standart SIM turi'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='battery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botapp.batteryrange', verbose_name='Batareya holati'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='botapp.color', verbose_name='Rang'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='has_box',
            field=models.BooleanField(default=True, verbose_name='Quti bor'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='manual_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Maxsus hollarda qo'shimcha +/- (dollar)", max_digits=15, verbose_name="Qo'lda sozlash ($)"),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='botapp.iphonemodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='note',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='sim_type',
            field=models.CharField(choices=[('physical', 'SIM karta'), ('esim', 'eSIM')], max_length=20, verbose_name='SIM turi'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botapp.storageoption', verbose_name='Xotira hajmi'),
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
        migrations.AlterField(
            model_name='storageoption',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='Bu standart (eng katta) xotira', verbose_name='Standart xotira'),
        ),
        migrations.AlterField(
            model_name='storageoption',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='botapp.iphonemodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='storageoption',
            name='price_difference',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standart xotiraga nisbatan (dollar). Masalan: 64GB=-600', max_digits=15, verbose_name='Narx farqi ($)'),
        ),
        migrations.CreateModel(
            name='DamageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Guruh nomi')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_groups', to='botapp.iphonemodel', verbose_name='Model')),
                ('damages', models.ManyToManyField(to='botapp.damagetype', verbose_name='Shikastlar')),
            ],
            options={
                'verbose_name': 'Shikast guruhi',
                'verbose_name_plural': 'Shikast guruhlari',
                'ordering': ['model', 'name'],
                'unique_together': {('model', 'name')},
            },
        ),
        migrations.AddField(
            model_name='priceentry',
            name='damage_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botapp.damagegroup', verbose_name='Shikast guruhi'),
        ),
        migrations.DeleteModel(
            name='ReplacedPart',
        ),
        migrations.DeleteModel(
            name='ReplacedPartCombination',
        ),
    ]
