# Generated by Django 5.2.9 on 2025-12-11 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0011_damagetype_remove_replacedpartcombination_parts_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='damagegroup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='damagegroup',
            name='damages',
        ),
        migrations.RemoveField(
            model_name='damagegroup',
            name='model',
        ),
        migrations.RemoveField(
            model_name='priceentry',
            name='damage_group',
        ),
        migrations.RemoveField(
            model_name='iphonemodel',
            name='damage_0_15_discount',
        ),
        migrations.RemoveField(
            model_name='iphonemodel',
            name='damage_15_30_discount',
        ),
        migrations.RemoveField(
            model_name='iphonemodel',
            name='damage_30_50_discount',
        ),
        migrations.RemoveField(
            model_name='priceentry',
            name='damage_discount',
        ),
        migrations.RemoveField(
            model_name='priceentry',
            name='damage_percentage',
        ),
        migrations.CreateModel(
            name='ReplacedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('battery', 'Batareyka'), ('back_cover', 'Krishka'), ('speaker', 'Kalonka'), ('glass', 'Oyna'), ('screen', 'Ekran'), ('camera', 'Kamera'), ('broken', 'Qirilgan'), ('body', 'Korpus')], max_length=20, verbose_name='Qism nomi')),
                ('price_reduction', models.DecimalField(decimal_places=2, default=0, help_text="Faqat bu qism almashgan bo'lsa. Masalan: Ekran = -100", max_digits=15, verbose_name='Alohida narx ($)')),
                ('description', models.TextField(blank=True, verbose_name="Ta'rif")),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced_parts', to='botapp.iphonemodel', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Almashgan qism (alohida)',
                'verbose_name_plural': 'Almashgan qismlar (alohida)',
                'ordering': ['model', 'order', 'part_type'],
                'unique_together': {('model', 'part_type')},
            },
        ),
        migrations.AddField(
            model_name='priceentry',
            name='replaced_parts',
            field=models.ManyToManyField(blank=True, help_text='Telefonda almashtirilgan qismlar (bir nechta tanlash mumkin)', to='botapp.replacedpart', verbose_name='Almashgan qismlar'),
        ),
        migrations.CreateModel(
            name='ReplacedPartGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Masalan: 'Ekran + Batareyka'", max_length=200, verbose_name='Guruh nomi')),
                ('group_discount', models.DecimalField(decimal_places=2, default=0, help_text="Bu guruh tanlanganda ANIQ qancha ayriladi. Masalan: -125 (o'rniga -150)", max_digits=15, verbose_name='Guruh narxi ($)')),
                ('priority', models.IntegerField(default=0, help_text='3 ta qism > 2 ta qism. Yuqori raqam birinchi tekshiriladi.', verbose_name='Ustuvorlik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_groups', to='botapp.iphonemodel', verbose_name='Model')),
                ('parts', models.ManyToManyField(help_text='Guruhga kiruvchi qismlar', to='botapp.replacedpart', verbose_name='Qismlar')),
            ],
            options={
                'verbose_name': 'Guruhli chegirma',
                'verbose_name_plural': 'Guruhli chegirmalar',
                'ordering': ['model', '-priority', 'name'],
                'unique_together': {('model', 'name')},
            },
        ),
        migrations.AddField(
            model_name='priceentry',
            name='applied_group',
            field=models.ForeignKey(blank=True, editable=False, help_text='Avtomatik topilgan guruhli chegirma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='botapp.replacedpartgroup', verbose_name="Qo'llangan guruh"),
        ),
        migrations.DeleteModel(
            name='DamageType',
        ),
        migrations.DeleteModel(
            name='DamageGroup',
        ),
    ]
