# Generated by Django 5.2.9 on 2025-12-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0012_alter_damagegroup_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacedpartgroup',
            name='parts',
            field=models.ManyToManyField(help_text="Guruhga kiruvchi qismlar (kamida 2 ta). ⚠️ Oyna va Ekran birgalikda BO'LMAYDI!", to='botapp.replacedpart', verbose_name='Qismlar'),
        ),
    ]
