# Generated by Django 5.2.9 on 2025-12-11 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0013_alter_replacedpartgroup_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceentry',
            name='applied_group',
        ),
        migrations.AlterField(
            model_name='priceentry',
            name='replaced_parts',
            field=models.ManyToManyField(blank=True, help_text="Agar kombinatsiya tanlangan bo'lsa, bu maydon ishlatilmaydi", to='botapp.replacedpart', verbose_name='Almashgan qismlar (alohida)'),
        ),
        migrations.CreateModel(
            name='ReplacedPartCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Masalan: 'Ekran + Batareyka'", max_length=200, verbose_name='Kombinatsiya nomi')),
                ('custom_price', models.DecimalField(decimal_places=2, default=0, help_text="Bu kombinatsiya tanlanganda QO'SHILADIGAN/AYRILADIGAN narx. Masalan: -125 yoki -200", max_digits=15, verbose_name='Kombinatsiya narxi ($)')),
                ('priority', models.IntegerField(default=0, help_text='3 ta qism > 2 ta qism. Yuqori raqam birinchi tekshiriladi.', verbose_name='Ustuvorlik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_combinations', to='botapp.iphonemodel', verbose_name='Model')),
                ('parts', models.ManyToManyField(help_text="Kombinatsiyaga kiruvchi qismlar (2-3 ta). ⚠️ Oyna va Ekran birgalikda BO'LMAYDI!", to='botapp.replacedpart', verbose_name='Qismlar')),
            ],
            options={
                'verbose_name': 'Qismlar kombinatsiyasi',
                'verbose_name_plural': 'Qismlar kombinatsiyalari',
                'ordering': ['model', '-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='priceentry',
            name='combination',
            field=models.ForeignKey(blank=True, help_text="Agar telefonda qismlar kombinatsiyasi bo'lsa tanlang", null=True, on_delete=django.db.models.deletion.SET_NULL, to='botapp.replacedpartcombination', verbose_name='Kombinatsiya'),
        ),
        migrations.DeleteModel(
            name='ReplacedPartGroup',
        ),
    ]
