# Generated by Django 5.2.9 on 2025-12-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0014_remove_priceentry_applied_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacedpart',
            name='part_type',
            field=models.CharField(choices=[('battery', 'Batareyka'), ('back_cover', 'Krishka'), ('face_id', 'Face ID'), ('glass', 'Oyna'), ('screen', 'Ekran'), ('camera', 'Kamera'), ('broken', 'Qirilgan'), ('body', 'Korpus')], max_length=20, verbose_name='Qism nomi'),
        ),
    ]
